// flow-typed signature: fb5c012e4d34d3c1b1f134373e899f09
// flow-typed version: <<STUB>>/@turf/boolean-within_v^6.0.1/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/boolean-within'
 *
 * Fill this stub out by replacing all the `any` actionTypes.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/boolean-within' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@turf/boolean-within/index' {
  declare module.exports: $Exports<'@turf/boolean-within'>;
}
declare module '@turf/boolean-within/index.js' {
  declare module.exports: $Exports<'@turf/boolean-within'>;
}
