// @flow
export const INVITATION = "INVITATION";
export const TEAM_MESSAGE = "TEAM_MESSAGE";
export const GLOBAL_MESSAGE = "GLOBAL_MESSAGE";
export const TEAM_LEADER_MESSAGE = "TEAM_LEADER_MESSAGE";
export const REQUEST_TO_JOIN = "REQUEST_TO_JOIN";
