// flow-typed signature: 02804eed8b99f7ec6cc299383e8c0866
// flow-typed version: <<STUB>>/@shoutem/animation_v^0.12.3/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@shoutem/animation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@shoutem/animation" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@shoutem/animation/src/animations/animations" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/animations/FadeIn" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/animations/FadeOut" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/animations/HeroHeader" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/animations/Parallax" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/animations/Rotate" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/animations/Slide/Slide" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/animations/Slide/SlideIn" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/animations/Slide/SlideOut" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/animations/View" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/animations/ZoomIn" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/animations/ZoomOut" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/components/connectAnimation" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/components/measure" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/components/ZoomableComponent" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/drivers/DriverBase" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/drivers/DriverShape" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/drivers/ScrollDriver" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/drivers/SpringDriver" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/drivers/TimingDriver" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/drivers/TouchableDriver" {
  declare module.exports: any;
}

declare module "@shoutem/animation/src/utils/animated-style" {
  declare module.exports: any;
}

// Filename aliases
declare module "@shoutem/animation/index" {
  declare module.exports: $Exports<'@shoutem/animation'>;
}
declare module "@shoutem/animation/index.js" {
  declare module.exports: $Exports<'@shoutem/animation'>;
}
declare module "@shoutem/animation/src/animations/animations.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/animations/animations'>;
}
declare module "@shoutem/animation/src/animations/FadeIn.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/animations/FadeIn'>;
}
declare module "@shoutem/animation/src/animations/FadeOut.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/animations/FadeOut'>;
}
declare module "@shoutem/animation/src/animations/HeroHeader.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/animations/HeroHeader'>;
}
declare module "@shoutem/animation/src/animations/Parallax.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/animations/Parallax'>;
}
declare module "@shoutem/animation/src/animations/Rotate.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/animations/Rotate'>;
}
declare module "@shoutem/animation/src/animations/Slide/Slide.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/animations/Slide/Slide'>;
}
declare module "@shoutem/animation/src/animations/Slide/SlideIn.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/animations/Slide/SlideIn'>;
}
declare module "@shoutem/animation/src/animations/Slide/SlideOut.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/animations/Slide/SlideOut'>;
}
declare module "@shoutem/animation/src/animations/View.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/animations/View'>;
}
declare module "@shoutem/animation/src/animations/ZoomIn.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/animations/ZoomIn'>;
}
declare module "@shoutem/animation/src/animations/ZoomOut.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/animations/ZoomOut'>;
}
declare module "@shoutem/animation/src/components/connectAnimation.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/components/connectAnimation'>;
}
declare module "@shoutem/animation/src/components/measure.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/components/measure'>;
}
declare module "@shoutem/animation/src/components/ZoomableComponent.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/components/ZoomableComponent'>;
}
declare module "@shoutem/animation/src/drivers/DriverBase.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/drivers/DriverBase'>;
}
declare module "@shoutem/animation/src/drivers/DriverShape.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/drivers/DriverShape'>;
}
declare module "@shoutem/animation/src/drivers/ScrollDriver.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/drivers/ScrollDriver'>;
}
declare module "@shoutem/animation/src/drivers/SpringDriver.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/drivers/SpringDriver'>;
}
declare module "@shoutem/animation/src/drivers/TimingDriver.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/drivers/TimingDriver'>;
}
declare module "@shoutem/animation/src/drivers/TouchableDriver.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/drivers/TouchableDriver'>;
}
declare module "@shoutem/animation/src/utils/animated-style.js" {
  declare module.exports: $Exports<'@shoutem/animation/src/utils/animated-style'>;
}
