// flow-typed signature: ca2f89cdc385d5f2a754bbe61e691f24
// flow-typed version: <<STUB>>/@shoutem/cli_v^0.10.11/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@shoutem/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@shoutem/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@shoutem/cli/config/services' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/builder' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/clone' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/configure' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/extension' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/extension/add' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/extension/publish' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/init' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/install' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/last-error' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/login' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/logout' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/pack' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/page' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/page/add' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/publish' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/push' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/run' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/schema' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/schema/add' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/screen' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/screen/add' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/shortcut' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/shortcut/add' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/show' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/theme' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/theme/add' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/uninstall' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/use' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/cli/whoami' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/clients/_tests_/auth-service.spec' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/clients/_tests_/extension-manager' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/clients/app-manager' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/clients/auth-service' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/clients/cli-paths' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/clients/extension-manager' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/clients/json-api-client' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/clients/legacy-service' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/clients/local-extensions' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/clients/server-env' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/clients/url-shortener' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/commands/clone' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/commands/confirm-admin-action' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/commands/init' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/commands/install' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/commands/login' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/commands/logout' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/commands/publish' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/commands/push-all' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/commands/push' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/commands/qr-generator' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/commands/run' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/commands/schema' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/commands/show' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/commands/theme' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/commands/update-cli' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/home-dir' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/scripts/shoutem-run' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/analytics' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/app-selector' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/builder' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/cache-env' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/cache' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/cli-parsing' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/command-exists' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/confirmer' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/data' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/decompress' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/diff' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/error-handler' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/ext-js-generator' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/extension-template' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/extension' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/extlint' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/linker' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/logger' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/multiglob' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/node' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/npm' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/npmjs' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/packer' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/page' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/platform' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/progress-bar' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/react-native' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/screen' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/shortcut' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/spinner' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/stream-listener' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/stream-matcher' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/template' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/tunnel' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/validation' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/services/yarn' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/shoutem' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/extension-js/app/extension' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/extension-js/server/src/extension' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/extension-js/template-init' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/init/{{devName}}.{{extJson.name}}/app/const' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/init/{{devName}}.{{extJson.name}}/app' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/init/{{devName}}.{{extJson.name}}/server/src/const' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/init/{{devName}}.{{extJson.name}}/server/src' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/init/template-init' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/screen/app/screens/{{screenName}}' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/screen/template-init' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-blank/template-init' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-html-extension/server/pages/{{pageDirectoryName}}' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-html-shortcut/server/pages/{{pageDirectoryName}}' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-html/template-init' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/configureStore' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/main' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/page/connectPage' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/page' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/page/Page' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/page/PageProvider' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/reducers' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/syncStateEngine' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/syncStateEngine/SyncStateEngineProvider' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/webpack/devServer' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/webpack/env' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/webpack/moduleRules' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/webpack/plugins' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/webpack/webpack.config' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react-bin/template-init' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react-extension/server/src/pages/{{pageDirectoryName}}/{{pageClassName}}' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react-extension/server/src/pages/{{pageDirectoryName}}' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react-shortcut/server/src/pages/{{pageDirectoryName}}/{{pageClassName}}' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react-shortcut/server/src/pages/{{pageDirectoryName}}' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page-react/template-init' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/settings-page/template-init' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/shortcut/template-init' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/theme/app/themes/{{themeName}}' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/templates/theme/template-init' {
  declare module.exports: any;
}

declare module '@shoutem/cli/src/user_messages' {
  declare module.exports: any;
}

// Filename aliases
declare module '@shoutem/cli/config/services.js' {
  declare module.exports: $Exports<'@shoutem/cli/config/services'>;
}
declare module '@shoutem/cli/src/cli.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli'>;
}
declare module '@shoutem/cli/src/cli/builder.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/builder'>;
}
declare module '@shoutem/cli/src/cli/clone.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/clone'>;
}
declare module '@shoutem/cli/src/cli/configure.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/configure'>;
}
declare module '@shoutem/cli/src/cli/extension.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/extension'>;
}
declare module '@shoutem/cli/src/cli/extension/add.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/extension/add'>;
}
declare module '@shoutem/cli/src/cli/extension/publish.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/extension/publish'>;
}
declare module '@shoutem/cli/src/cli/init.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/init'>;
}
declare module '@shoutem/cli/src/cli/install.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/install'>;
}
declare module '@shoutem/cli/src/cli/last-error.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/last-error'>;
}
declare module '@shoutem/cli/src/cli/login.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/login'>;
}
declare module '@shoutem/cli/src/cli/logout.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/logout'>;
}
declare module '@shoutem/cli/src/cli/pack.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/pack'>;
}
declare module '@shoutem/cli/src/cli/page.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/page'>;
}
declare module '@shoutem/cli/src/cli/page/add.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/page/add'>;
}
declare module '@shoutem/cli/src/cli/publish.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/publish'>;
}
declare module '@shoutem/cli/src/cli/push.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/push'>;
}
declare module '@shoutem/cli/src/cli/run.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/run'>;
}
declare module '@shoutem/cli/src/cli/schema.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/schema'>;
}
declare module '@shoutem/cli/src/cli/schema/add.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/schema/add'>;
}
declare module '@shoutem/cli/src/cli/screen.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/screen'>;
}
declare module '@shoutem/cli/src/cli/screen/add.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/screen/add'>;
}
declare module '@shoutem/cli/src/cli/shortcut.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/shortcut'>;
}
declare module '@shoutem/cli/src/cli/shortcut/add.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/shortcut/add'>;
}
declare module '@shoutem/cli/src/cli/show.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/show'>;
}
declare module '@shoutem/cli/src/cli/theme.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/theme'>;
}
declare module '@shoutem/cli/src/cli/theme/add.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/theme/add'>;
}
declare module '@shoutem/cli/src/cli/uninstall.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/uninstall'>;
}
declare module '@shoutem/cli/src/cli/use.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/use'>;
}
declare module '@shoutem/cli/src/cli/whoami.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/cli/whoami'>;
}
declare module '@shoutem/cli/src/clients/_tests_/auth-service.spec.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/clients/_tests_/auth-service.spec'>;
}
declare module '@shoutem/cli/src/clients/_tests_/extension-manager.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/clients/_tests_/extension-manager'>;
}
declare module '@shoutem/cli/src/clients/app-manager.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/clients/app-manager'>;
}
declare module '@shoutem/cli/src/clients/auth-service.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/clients/auth-service'>;
}
declare module '@shoutem/cli/src/clients/cli-paths.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/clients/cli-paths'>;
}
declare module '@shoutem/cli/src/clients/extension-manager.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/clients/extension-manager'>;
}
declare module '@shoutem/cli/src/clients/json-api-client.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/clients/json-api-client'>;
}
declare module '@shoutem/cli/src/clients/legacy-service.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/clients/legacy-service'>;
}
declare module '@shoutem/cli/src/clients/local-extensions.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/clients/local-extensions'>;
}
declare module '@shoutem/cli/src/clients/server-env.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/clients/server-env'>;
}
declare module '@shoutem/cli/src/clients/url-shortener.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/clients/url-shortener'>;
}
declare module '@shoutem/cli/src/commands/clone.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/commands/clone'>;
}
declare module '@shoutem/cli/src/commands/confirm-admin-action.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/commands/confirm-admin-action'>;
}
declare module '@shoutem/cli/src/commands/init.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/commands/init'>;
}
declare module '@shoutem/cli/src/commands/install.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/commands/install'>;
}
declare module '@shoutem/cli/src/commands/login.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/commands/login'>;
}
declare module '@shoutem/cli/src/commands/logout.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/commands/logout'>;
}
declare module '@shoutem/cli/src/commands/publish.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/commands/publish'>;
}
declare module '@shoutem/cli/src/commands/push-all.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/commands/push-all'>;
}
declare module '@shoutem/cli/src/commands/push.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/commands/push'>;
}
declare module '@shoutem/cli/src/commands/qr-generator.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/commands/qr-generator'>;
}
declare module '@shoutem/cli/src/commands/run.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/commands/run'>;
}
declare module '@shoutem/cli/src/commands/schema.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/commands/schema'>;
}
declare module '@shoutem/cli/src/commands/show.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/commands/show'>;
}
declare module '@shoutem/cli/src/commands/theme.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/commands/theme'>;
}
declare module '@shoutem/cli/src/commands/update-cli.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/commands/update-cli'>;
}
declare module '@shoutem/cli/src/home-dir.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/home-dir'>;
}
declare module '@shoutem/cli/src/scripts/shoutem-run.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/scripts/shoutem-run'>;
}
declare module '@shoutem/cli/src/services/analytics.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/analytics'>;
}
declare module '@shoutem/cli/src/services/app-selector.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/app-selector'>;
}
declare module '@shoutem/cli/src/services/builder.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/builder'>;
}
declare module '@shoutem/cli/src/services/cache-env.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/cache-env'>;
}
declare module '@shoutem/cli/src/services/cache.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/cache'>;
}
declare module '@shoutem/cli/src/services/cli-parsing.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/cli-parsing'>;
}
declare module '@shoutem/cli/src/services/command-exists.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/command-exists'>;
}
declare module '@shoutem/cli/src/services/confirmer.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/confirmer'>;
}
declare module '@shoutem/cli/src/services/data.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/data'>;
}
declare module '@shoutem/cli/src/services/decompress.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/decompress'>;
}
declare module '@shoutem/cli/src/services/diff.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/diff'>;
}
declare module '@shoutem/cli/src/services/error-handler.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/error-handler'>;
}
declare module '@shoutem/cli/src/services/ext-js-generator.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/ext-js-generator'>;
}
declare module '@shoutem/cli/src/services/extension-template.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/extension-template'>;
}
declare module '@shoutem/cli/src/services/extension.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/extension'>;
}
declare module '@shoutem/cli/src/services/extlint/index' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/extlint'>;
}
declare module '@shoutem/cli/src/services/extlint/index.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/extlint'>;
}
declare module '@shoutem/cli/src/services/linker.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/linker'>;
}
declare module '@shoutem/cli/src/services/logger.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/logger'>;
}
declare module '@shoutem/cli/src/services/multiglob.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/multiglob'>;
}
declare module '@shoutem/cli/src/services/node.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/node'>;
}
declare module '@shoutem/cli/src/services/npm.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/npm'>;
}
declare module '@shoutem/cli/src/services/npmjs.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/npmjs'>;
}
declare module '@shoutem/cli/src/services/packer.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/packer'>;
}
declare module '@shoutem/cli/src/services/page.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/page'>;
}
declare module '@shoutem/cli/src/services/platform.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/platform'>;
}
declare module '@shoutem/cli/src/services/progress-bar.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/progress-bar'>;
}
declare module '@shoutem/cli/src/services/react-native.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/react-native'>;
}
declare module '@shoutem/cli/src/services/screen.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/screen'>;
}
declare module '@shoutem/cli/src/services/shortcut.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/shortcut'>;
}
declare module '@shoutem/cli/src/services/spinner.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/spinner'>;
}
declare module '@shoutem/cli/src/services/stream-listener.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/stream-listener'>;
}
declare module '@shoutem/cli/src/services/stream-matcher.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/stream-matcher'>;
}
declare module '@shoutem/cli/src/services/template.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/template'>;
}
declare module '@shoutem/cli/src/services/tunnel.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/tunnel'>;
}
declare module '@shoutem/cli/src/services/validation.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/validation'>;
}
declare module '@shoutem/cli/src/services/yarn.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/services/yarn'>;
}
declare module '@shoutem/cli/src/shoutem.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/shoutem'>;
}
declare module '@shoutem/cli/src/templates/extension-js/app/extension.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/extension-js/app/extension'>;
}
declare module '@shoutem/cli/src/templates/extension-js/server/src/extension.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/extension-js/server/src/extension'>;
}
declare module '@shoutem/cli/src/templates/extension-js/template-init.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/extension-js/template-init'>;
}
declare module '@shoutem/cli/src/templates/init/{{devName}}.{{extJson.name}}/app/const.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/init/{{devName}}.{{extJson.name}}/app/const'>;
}
declare module '@shoutem/cli/src/templates/init/{{devName}}.{{extJson.name}}/app/index' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/init/{{devName}}.{{extJson.name}}/app'>;
}
declare module '@shoutem/cli/src/templates/init/{{devName}}.{{extJson.name}}/app/index.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/init/{{devName}}.{{extJson.name}}/app'>;
}
declare module '@shoutem/cli/src/templates/init/{{devName}}.{{extJson.name}}/server/src/const.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/init/{{devName}}.{{extJson.name}}/server/src/const'>;
}
declare module '@shoutem/cli/src/templates/init/{{devName}}.{{extJson.name}}/server/src/index' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/init/{{devName}}.{{extJson.name}}/server/src'>;
}
declare module '@shoutem/cli/src/templates/init/{{devName}}.{{extJson.name}}/server/src/index.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/init/{{devName}}.{{extJson.name}}/server/src'>;
}
declare module '@shoutem/cli/src/templates/init/template-init.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/init/template-init'>;
}
declare module '@shoutem/cli/src/templates/screen/app/screens/{{screenName}}.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/screen/app/screens/{{screenName}}'>;
}
declare module '@shoutem/cli/src/templates/screen/template-init.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/screen/template-init'>;
}
declare module '@shoutem/cli/src/templates/settings-page-blank/template-init.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-blank/template-init'>;
}
declare module '@shoutem/cli/src/templates/settings-page-html-extension/server/pages/{{pageDirectoryName}}/index' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-html-extension/server/pages/{{pageDirectoryName}}'>;
}
declare module '@shoutem/cli/src/templates/settings-page-html-extension/server/pages/{{pageDirectoryName}}/index.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-html-extension/server/pages/{{pageDirectoryName}}'>;
}
declare module '@shoutem/cli/src/templates/settings-page-html-shortcut/server/pages/{{pageDirectoryName}}/index' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-html-shortcut/server/pages/{{pageDirectoryName}}'>;
}
declare module '@shoutem/cli/src/templates/settings-page-html-shortcut/server/pages/{{pageDirectoryName}}/index.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-html-shortcut/server/pages/{{pageDirectoryName}}'>;
}
declare module '@shoutem/cli/src/templates/settings-page-html/template-init.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-html/template-init'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/configureStore.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-bin/server/bin/configureStore'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/index' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-bin/server/bin'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/index.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-bin/server/bin'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/main.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-bin/server/bin/main'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/page/connectPage.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-bin/server/bin/page/connectPage'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/page/index' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-bin/server/bin/page'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/page/index.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-bin/server/bin/page'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/page/Page.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-bin/server/bin/page/Page'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/page/PageProvider.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-bin/server/bin/page/PageProvider'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/reducers.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-bin/server/bin/reducers'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/syncStateEngine/index' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-bin/server/bin/syncStateEngine'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/syncStateEngine/index.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-bin/server/bin/syncStateEngine'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/syncStateEngine/SyncStateEngineProvider.jsx' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-bin/server/bin/syncStateEngine/SyncStateEngineProvider'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/webpack/devServer.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-bin/server/bin/webpack/devServer'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/webpack/env.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-bin/server/bin/webpack/env'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/webpack/moduleRules.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-bin/server/bin/webpack/moduleRules'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/webpack/plugins.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-bin/server/bin/webpack/plugins'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-bin/server/bin/webpack/webpack.config.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-bin/server/bin/webpack/webpack.config'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-bin/template-init.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-bin/template-init'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-extension/server/src/pages/{{pageDirectoryName}}/{{pageClassName}}.jsx' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-extension/server/src/pages/{{pageDirectoryName}}/{{pageClassName}}'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-extension/server/src/pages/{{pageDirectoryName}}/index' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-extension/server/src/pages/{{pageDirectoryName}}'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-extension/server/src/pages/{{pageDirectoryName}}/index.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-extension/server/src/pages/{{pageDirectoryName}}'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-shortcut/server/src/pages/{{pageDirectoryName}}/{{pageClassName}}.jsx' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-shortcut/server/src/pages/{{pageDirectoryName}}/{{pageClassName}}'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-shortcut/server/src/pages/{{pageDirectoryName}}/index' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-shortcut/server/src/pages/{{pageDirectoryName}}'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react-shortcut/server/src/pages/{{pageDirectoryName}}/index.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react-shortcut/server/src/pages/{{pageDirectoryName}}'>;
}
declare module '@shoutem/cli/src/templates/settings-page-react/template-init.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page-react/template-init'>;
}
declare module '@shoutem/cli/src/templates/settings-page/template-init.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/settings-page/template-init'>;
}
declare module '@shoutem/cli/src/templates/shortcut/template-init.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/shortcut/template-init'>;
}
declare module '@shoutem/cli/src/templates/theme/app/themes/{{themeName}}.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/theme/app/themes/{{themeName}}'>;
}
declare module '@shoutem/cli/src/templates/theme/template-init.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/templates/theme/template-init'>;
}
declare module '@shoutem/cli/src/user_messages.js' {
  declare module.exports: $Exports<'@shoutem/cli/src/user_messages'>;
}
