// flow-typed signature: 8d8ba11d7d9dcb5ae752afb938e9d35c
// flow-typed version: <<STUB>>/@shoutem/theme_v^0.11.3/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@shoutem/theme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@shoutem/theme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@shoutem/theme/examples/Shapes' {
  declare module.exports: any;
}

declare module '@shoutem/theme/src/addons' {
  declare module.exports: any;
}

declare module '@shoutem/theme/src/connectStyle' {
  declare module.exports: any;
}

declare module '@shoutem/theme/src/mergeComponentAndThemeStyles' {
  declare module.exports: any;
}

declare module '@shoutem/theme/src/resolveComponentStyle' {
  declare module.exports: any;
}

declare module '@shoutem/theme/src/resolveIncludes' {
  declare module.exports: any;
}

declare module '@shoutem/theme/src/StyleNormalizer/normalizeStyle' {
  declare module.exports: any;
}

declare module '@shoutem/theme/src/StyleNormalizer/ShorthandsNormalizerFactory' {
  declare module.exports: any;
}

declare module '@shoutem/theme/src/StyleNormalizer/StyleNormalizer' {
  declare module.exports: any;
}

declare module '@shoutem/theme/src/StyleProvider' {
  declare module.exports: any;
}

declare module '@shoutem/theme/src/Theme' {
  declare module.exports: any;
}

declare module '@shoutem/theme/test-utils/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module '@shoutem/theme/examples/Shapes.js' {
  declare module.exports: $Exports<'@shoutem/theme/examples/Shapes'>;
}
declare module '@shoutem/theme/index' {
  declare module.exports: $Exports<'@shoutem/theme'>;
}
declare module '@shoutem/theme/index.js' {
  declare module.exports: $Exports<'@shoutem/theme'>;
}
declare module '@shoutem/theme/src/addons.js' {
  declare module.exports: $Exports<'@shoutem/theme/src/addons'>;
}
declare module '@shoutem/theme/src/connectStyle.js' {
  declare module.exports: $Exports<'@shoutem/theme/src/connectStyle'>;
}
declare module '@shoutem/theme/src/mergeComponentAndThemeStyles.js' {
  declare module.exports: $Exports<'@shoutem/theme/src/mergeComponentAndThemeStyles'>;
}
declare module '@shoutem/theme/src/resolveComponentStyle.js' {
  declare module.exports: $Exports<'@shoutem/theme/src/resolveComponentStyle'>;
}
declare module '@shoutem/theme/src/resolveIncludes.js' {
  declare module.exports: $Exports<'@shoutem/theme/src/resolveIncludes'>;
}
declare module '@shoutem/theme/src/StyleNormalizer/normalizeStyle.js' {
  declare module.exports: $Exports<'@shoutem/theme/src/StyleNormalizer/normalizeStyle'>;
}
declare module '@shoutem/theme/src/StyleNormalizer/ShorthandsNormalizerFactory.js' {
  declare module.exports: $Exports<'@shoutem/theme/src/StyleNormalizer/ShorthandsNormalizerFactory'>;
}
declare module '@shoutem/theme/src/StyleNormalizer/StyleNormalizer.js' {
  declare module.exports: $Exports<'@shoutem/theme/src/StyleNormalizer/StyleNormalizer'>;
}
declare module '@shoutem/theme/src/StyleProvider.js' {
  declare module.exports: $Exports<'@shoutem/theme/src/StyleProvider'>;
}
declare module '@shoutem/theme/src/Theme.js' {
  declare module.exports: $Exports<'@shoutem/theme/src/Theme'>;
}
declare module '@shoutem/theme/test-utils/setup.js' {
  declare module.exports: $Exports<'@shoutem/theme/test-utils/setup'>;
}
