tasks:
- before: >
      npm install &&
      npm install -g expo-cli
  command: expo start --host tunnel

ports:
- port: 19000-19002
  onOpen: ignore
- port: 4040
  onOpen: ignore
- port: 5037
  onOpen: ignore