---
language: node_js
node_js:
  - 10.16.3
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
  - npm install -g expo-cli
script:
  - npx jest --ci
jobs:
  include:
    - stage: deploy
      node_js: 10.16.3
      script:
        - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
        - yarn install
        - node write-config.js
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --non-interactive
