---
language: node_js
node_js:
  - 10.15.3
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
  - echo "export const firebaseConfig = {apiKey:${FIREBASE_API_KEY},authDomain:${FIREBASE_AUTH_DOMAIN},databaseURL:${FIREBASE_DATABASE_URL},projectId:${FIREBASE_PROJECT_ID},storageBucket:${FIREBASE_STORAGE_BUCKET},messagingSenderId:${FIREBASE_MESSAGING_SENDER_ID}}" > ./data-sources/firebase-config.js
script:
  - npx jest --ci
jobs:
  include:
    - stage: deploy
      node_js: 10.15.3
      script:
        - yarn install
        - jest
        - npm install -g expo-cli
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --non-interactive
