---
language: node_js
node_js:
  - 10.15.3
cache:
  directories:
    - ~/.npm
    - .jest
    -
before_script:
  - npm install -g npm@latest
  - echo ${ENVIROMENT} >> .environment.js
script:
  - npx jest --ci
jobs:
  include:
    - stage: deploy
      node_js: 10.15.3
      script:
        - yarn install
        - jest
        - npm install -g expo-cli
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --non-interactive
