// flow-typed signature: 41aa466023e2f65cde5d7f67644eac30
// flow-typed version: <<STUB>>/@actionTypes/react-navigation_v^3.0.8/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@actionTypes/react-navigation'
 *
 * Fill this stub out by replacing all the `any` actionTypes.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-navigation' {
  declare module.exports: any;
}
