// flow-typed signature: 60e5de1fbc05e1017a51c180026fe0cc
// flow-typed version: <<STUB>>/expo-intent-launcher_v^6.0.0/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-intent-launcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-intent-launcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-intent-launcher/build/ExpoIntentLauncher' {
  declare module.exports: any;
}

declare module 'expo-intent-launcher/build/ExpoIntentLauncher.web' {
  declare module.exports: any;
}

declare module 'expo-intent-launcher/build/IntentLauncher' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-intent-launcher/build/ExpoIntentLauncher.js' {
  declare module.exports: $Exports<'expo-intent-launcher/build/ExpoIntentLauncher'>;
}
declare module 'expo-intent-launcher/build/ExpoIntentLauncher.web.js' {
  declare module.exports: $Exports<'expo-intent-launcher/build/ExpoIntentLauncher.web'>;
}
declare module 'expo-intent-launcher/build/IntentLauncher.js' {
  declare module.exports: $Exports<'expo-intent-launcher/build/IntentLauncher'>;
}
