// flow-typed signature: b76e0f5c9457debdf7f16f3d10ed16e3
// flow-typed version: <<STUB>>/expo-module-scripts_v^1.0.1/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-module-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-module-scripts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-module-scripts/babel.config.base' {
  declare module.exports: any;
}

declare module 'expo-module-scripts/bin/expo-module' {
  declare module.exports: any;
}

declare module 'expo-module-scripts/createJestPreset' {
  declare module.exports: any;
}

declare module 'expo-module-scripts/eslintrc.base' {
  declare module.exports: any;
}

declare module 'expo-module-scripts/jest-preset' {
  declare module.exports: any;
}

declare module 'expo-module-scripts/universal/jest-preset' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-module-scripts/babel.config.base.js' {
  declare module.exports: $Exports<'expo-module-scripts/babel.config.base'>;
}
declare module 'expo-module-scripts/bin/expo-module.js' {
  declare module.exports: $Exports<'expo-module-scripts/bin/expo-module'>;
}
declare module 'expo-module-scripts/createJestPreset.js' {
  declare module.exports: $Exports<'expo-module-scripts/createJestPreset'>;
}
declare module 'expo-module-scripts/eslintrc.base.js' {
  declare module.exports: $Exports<'expo-module-scripts/eslintrc.base'>;
}
declare module 'expo-module-scripts/index' {
  declare module.exports: $Exports<'expo-module-scripts'>;
}
declare module 'expo-module-scripts/index.js' {
  declare module.exports: $Exports<'expo-module-scripts'>;
}
declare module 'expo-module-scripts/jest-preset.js' {
  declare module.exports: $Exports<'expo-module-scripts/jest-preset'>;
}
declare module 'expo-module-scripts/universal/jest-preset.js' {
  declare module.exports: $Exports<'expo-module-scripts/universal/jest-preset'>;
}
