// flow-typed signature: d553839ffc7d8cb85c7d7a5da0823047
// flow-typed version: <<STUB>>/expo-contacts_v^6.0.0/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-contacts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "expo-contacts" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "expo-contacts/build/Contacts" {
  declare module.exports: any;
}

declare module "expo-contacts/build/ExpoContacts" {
  declare module.exports: any;
}

declare module "expo-contacts/build/ExpoContacts.web" {
  declare module.exports: any;
}

// Filename aliases
declare module "expo-contacts/build/Contacts.js" {
  declare module.exports: $Exports<'expo-contacts/build/Contacts'>;
}
declare module "expo-contacts/build/ExpoContacts.js" {
  declare module.exports: $Exports<'expo-contacts/build/ExpoContacts'>;
}
declare module "expo-contacts/build/ExpoContacts.web.js" {
  declare module.exports: $Exports<'expo-contacts/build/ExpoContacts.web'>;
}
