// flow-typed signature: d3ea01718e98088872ac188f411037c3
// flow-typed version: <<STUB>>/md5-hash_v^1.0.1/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'md5-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "md5-hash" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "md5-hash/dist" {
  declare module.exports: any;
}

// Filename aliases
declare module "md5-hash/dist/index" {
  declare module.exports: $Exports<'md5-hash/dist'>;
}
declare module "md5-hash/dist/index.js" {
  declare module.exports: $Exports<'md5-hash/dist'>;
}
