// flow-typed signature: c61b0022905760578436f23d20f24cdf
// flow-typed version: <<STUB>>/react-native-checkbox_v^2.0.0/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-checkbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-native-checkbox" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-native-checkbox/checkbox" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-native-checkbox/checkbox.js" {
  declare module.exports: $Exports<'react-native-checkbox/checkbox'>;
}
