// flow-typed signature: c58439eb1a5980146b93e14daa33c81b
// flow-typed version: <<STUB>>/react-native-autocomplete-input_v^4.1.0/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-autocomplete-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-native-autocomplete-input" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module "react-native-autocomplete-input/index" {
  declare module.exports: $Exports<'react-native-autocomplete-input'>;
}
declare module "react-native-autocomplete-input/index.js" {
  declare module.exports: $Exports<'react-native-autocomplete-input'>;
}
