# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master

    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Yarn
          command: yarn install

      - run:
          name: Install Expo
          command: yarn global add expo-cli

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # lint the code
      - run:
          name: Code Linting
          command: yarn lint

      # run tests!
      - run:
          name: Unit Testing
          command: yarn test-ci

      # Config Firebase
      - run:
          name: Configure App to Use QA DB
          command: node write-firebase-config.js

      - run:
          name: Install Firebase Function Deps
          command: cd functions && npm install

      - run:
          name: Deploy Master to DEV Firebase Functions
          command: ./node_modules/.bin/firebase deploy -P dev --only functions --token=$FIREBASE_DEPLOY_TOKEN

      - run:
          name: Deploy Master to DEV Firebase Storage Rules
          command: ./node_modules/.bin/firebase deploy -P dev --only storage --token=$FIREBASE_DEPLOY_TOKEN

      - run:
          name: Deploy Master to DEV Firestore Security Rules
          command: ./node_modules/.bin/firebase deploy -P dev --only firestore:rules --token=$FIREBASE_DEPLOY_TOKEN

      - run:
          name: Deploy Master to QA Firebase Functions
          command: ./node_modules/.bin/firebase deploy -P qa --only functions --token=$FIREBASE_DEPLOY_TOKEN

      - run:
          name: Deploy Master to QA Firebase Storage Rules
          command: ./node_modules/.bin/firebase deploy -P qa --only storage --token=$FIREBASE_DEPLOY_TOKEN

      - run:
          name: Deploy Master to QA Firestore Security Rules
          command: ./node_modules/.bin/firebase deploy -P qa --only firestore:rules --token=$FIREBASE_DEPLOY_TOKEN

      - run:
        name: Bump up the version
        command: |
          git config user.name $CIRCLE_USERNAME
          npm version patch -m "Bumped version number to %s [ci skip]"
          git push origin master
          git push --tags

      - run:
          name: Login into Expo
          command: npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD

      - run:
          name: Publish to Expo
          command: npx expo publish --non-interactive --max-workers 1 --release-channel $EXPO_RELEASE_CHANNEL
