export const NEW_MESSAGE = 'NEW_MESSAGE';
export const READ_MESSAGE = 'READ_MESSAGE';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const NO_CURRENT_USER = 'NO_CURRENT_USER';
export const CREATING_USER = 'CREATING_USER';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

export const GET_ABOUT_GREENUP_SUCCESS = 'GET_ABOUT_GREENUP_SUCCESS';
export const GET_ABOUT_GREENUP_FAIL = 'GET_ABOUT_GREENUP_FAIL';
export const GET_ABOUT_CONTACTS_SUCCESS = 'GET_ABOUT_CONTACTS_SUCCESS';
export const GET_ABOUT_CONTACTS_FAIL = 'GET_ABOUT_CONTACTS_FAIL';
export const RETRIEVE_CONTACTS_SUCCESS = 'RETRIEVE_CONTACTS_SUCCESS';
export const RETRIEVE_CONTACTS_FAIL = 'RETRIEVE_CONTACTS_FAIL';

export const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS';
export const SAVE_TEAM_SUCCESS = 'SAVE_TEAM_SUCCESS';
export const SAVE_TEAM_FAIL = 'SAVE_TEAM_FAIL';
export const SEARCH_TEAMS_SUCCESS = 'SEARCH_TEAMS_SUCCESS';
export const SELECT_TEAM = 'SELECT_TEAM';
export const SESSION_STARTED = 'SESSION_STARTED';
export const TRASH_DROP_SUCCESS = 'TRASH_DROP_SUCCESS';
export const TRASH_DROP_FAIL = 'TRASH_DROP_FAIL';
