export const NEW_MESSAGE = 'NEW_MESSAGE';
export const READ_MESSAGE = 'READ_MESSAGE';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const GET_ABOUT_CONTENT_SUCCESS = 'GET_ABOUT_CONTENT_SUCCESS';
export const GET_ABOUT_CONTENT_FAIL = 'GET_ABOUT_CONTENT_FAIL';
export const RETRIEVE_CONTACTS_SUCCESS = 'RETRIEVE_CONTACTS_SUCCESS';
export const RETRIEVE_CONTACTS_FAIL = 'RETRIEVE_CONTACTS_FAIL';
export const SEARCH_TEAMS_SUCCESS = 'SEARCH_TEAMS_SUCCESS';
