// flow-typed signature: 0a616332462abf8bd7b26110de63696a
// flow-typed version: <<STUB>>/@expo/samples_v3.0.3/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@expo/samples'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@expo/samples" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@expo/samples/ExpoConfigView" {
  declare module.exports: any;
}

declare module "@expo/samples/ExpoLinksView" {
  declare module.exports: any;
}

// Filename aliases
declare module "@expo/samples/ExpoConfigView.js" {
  declare module.exports: $Exports<'@expo/samples/ExpoConfigView'>;
}
declare module "@expo/samples/ExpoLinksView.js" {
  declare module.exports: $Exports<'@expo/samples/ExpoLinksView'>;
}
declare module "@expo/samples/index" {
  declare module.exports: $Exports<'@expo/samples'>;
}
declare module "@expo/samples/index.js" {
  declare module.exports: $Exports<'@expo/samples'>;
}
