export const vermontTowns = [
    'Addison', 'Albany', 'Alburgh', 'Andover', 'Arlington', 'Athens', 'Averill',
    'Bakersfield', 'Baltimore', 'Barnard', 'Barnet', 'Barre', 'Barton', 'Belvidere',
    'Bennington', 'Benson', 'Berkshire', 'Berlin', 'Bethel', 'Bloomfield', 'Bolton',
    'Bradford', 'Braintree', 'Brandon', 'Brattleboro', 'Bridgewater', 'Bridport', 'Brighton',
    'Bristol', 'Brookfield', 'Brookline', 'Brownington', 'Brunswick', 'Burke', 'Cabot', 'Calais',
    'Cambridge', 'Canaan', 'Castleton', 'Cavendish', 'Charleston', 'Charlotte', 'Chelsea',
    'Chester', 'Chittenden', 'Clarendon', 'Colchester', 'Concord', 'Corinth', 'Cornwall',
    'Coventry', 'Craftsbury', 'Danby', 'Danville', 'Derby', 'Dorset', 'Dover', 'Dummerston',
    'Duxbury', 'East Haven', 'East Montpelier', 'Eden', 'Elmore', 'Enosburgh', 'Essex',
    'Fair Haven', 'Fairfax', 'Fairfield', 'Fairlee', 'Fayston', 'Ferdinand', 'Ferrisburgh',
    'Fletcher', 'Franklin', 'Georgia', 'Glastenbury', 'Glover', 'Goshen', 'Grafton', 'Granby', 'Grand Isle',
    'Granville', 'Greensboro', 'Groton', 'Guildhall', 'Guilford', 'Halifax', 'Hancock',
    'Hardwick', 'Hartford', 'Hartland', 'Highgate', 'Hinesburg', 'Holland', 'Hubbardton',
    'Huntington', 'Hyde Park', 'Ira', 'Irasburg', 'Isle La Motte', 'Jamaica', 'Jay',
    'Jericho', 'Johnson', 'Killington', 'Kirby', 'Landgrove', 'Leicester', 'Lemington', 'Lewis',
    'Lincoln', 'Londonderry', 'Lowell', 'Ludlow', 'Lunenburg', 'Lyndon', 'Maidstone', 'Manchester',
    'Marlboro', 'Marshfield', 'Mendon', 'Middlebury', 'Middlesex', 'Middletown Springs', 'Milton',
    'Monkton', 'Montgomery', 'Moretown', 'Morgan', 'Morristown', 'Mount Holly', 'Mount Tabor', 'New Haven',
    'Newark', 'Newbury', 'Newfane', 'Newport', 'North Hero', 'Northfield', 'Norton', 'Norwich',
    'Orange', 'Orwell', 'Panton', 'Pawlet', 'Peacham', 'Peru',
    'Pittsfield', 'Pittsford', 'Plainfield', 'Plymouth', 'Pomfret', 'Poultney', 'Pownal', 'Proctor',
    'Putney', 'Randolph', 'Reading', 'Readsboro', 'Richford', 'Richmond', 'Ripton', 'Rochester',
    'Rockingham', 'Roxbury', 'Royalton', 'Rupert', 'Rutland', 'Ryegate', 'Salisbury', 'Sandgate', 'Searsburg',
    'Shaftsbury', 'Sharon', 'Sheffield', 'Shelburne', 'Sheldon', 'Shoreham', 'Shrewsbury', 'Somerset',
    'South Hero', 'Springfield', 'St.Albans', 'St.George', 'St.Johnsbury', 'Stamford', 'Stannard', 'Starksboro',
    'Stockbridge', 'Stowe', 'Strafford', 'Stratton', 'Sudbury', 'Sunderland', 'Sutton', 'Swanton',
    'Thetford', 'Tinmouth', 'Topsham', 'Townshend', 'Troy', 'Tunbridge', 'Underhill', 'Vernon', 'Vershire',
    'Victory', 'Waitsfield', 'Walden', 'Wallingford', 'Waltham', 'Wardsboro', 'Warren', 'Washington',
    'Waterbury', 'Waterford', 'Waterville', 'Weathersfield', 'Wells', 'West Fairlee', 'West Haven',
    'West Rutland', 'West Windsor', 'Westfield', 'Westford', 'Westminster', 'Westmore', 'Weston',
    'Weybridge', 'Wheelock', 'Whiting', 'Whitingham', 'Williamstown', 'Williston', 'Wilmington',
    'Windham', 'Windsor', 'Winhall', 'Wolcott', 'Woodbury', 'Woodford', 'Woodstock', 'Worcester',
    'Washington'
];