// flow-typed signature: 285abfd5fa450a94fc0ffb8a6511201f
// flow-typed version: <<STUB>>/firebase/firestore_v6.6.2/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebase/firestore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebase/firestore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firebase/firestore/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'firebase/firestore/dist/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firebase/firestore/dist/index.cjs.js' {
  declare module.exports: $Exports<'firebase/firestore/dist/index.cjs'>;
}
declare module 'firebase/firestore/dist/index.esm.js' {
  declare module.exports: $Exports<'firebase/firestore/dist/index.esm'>;
}
